#! /bin/bash

## define winestarter git source
wine_src=$HOME/.winestarter
## make a temp file for git fetch output and execute
temp=$(mktemp --tmpdir git.XXXXXXXX)
git fetch --dry-run &>$temp
## if the word master appears in log, then process, otherwise exit.
if [ $(cat $temp|grep -c "master") -eq 1 ]; then
	## send a notification to user desktop.
	win_icon=$wine_src/png/defaults/wine48r.png
	msg="Winestarter update on the run !"
	zenity --notification --window-icon=$win_icon --text="$msg"
fi
## got out of there
exit 0
